Implement Sort Command
CS2103JAN2017-W15-B3/main pull request #109
Opened 2017-03-20 12:58 UTC by gjlam95

Sorts tasks by end time

2017-03-20 15:19 UTC, mynameisyz requested changes

2017-03-20 15:19 UTC, mynameisyz commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +
Instead of using the method under testing (getSortedList) to generate the expected sorted list, try creating a sorted list by adding Tasks manually to the list in the sorted manner. Otherwise, the test will always pass as the expected data and test result data are generated by the same method.

2017-03-20 15:37 UTC, gjlam95 commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +
Roger!

2017-03-21 15:25 UTC, xbili requested changes
Just gotta extract the predicates for the if-else out, otherwise LGTM! 👍

2017-03-21 15:25 UTC, xbili commented on src/main/java/seedu/address/model/task/EndTimeComparator.java
> +            } else if (p.getEndTime().get().dateTime.isAfter(q.getEndTime().get().dateTime)) {
These predicates should be extracted out to a variable to make it more understandable and readable.

e.g. `boolean hasStartAndEnd = p.getStartTime().isPresent() && p.getEndTime().isPresent();`

2017-03-21 15:25 UTC, xbili commented on src/main/java/seedu/address/model/task/EndTimeComparator.java
> +        } else if (p.getEndTime().isPresent() || q.getEndTime().isPresent()) {
Same for this!

2017-03-21 15:38 UTC, mynameisyz approved these changes

2017-03-21 16:10 UTC, xbili approved these changes

2017-03-21 16:16 UTC, merged