Add schedule command and test cases
CS2103JAN2017-W15-B3/main pull request #172
Opened 2017-03-26 02:32 UTC by hlynn93

2017-03-26 12:50 UTC, xbili requested changes
I tried out this build. `mark` command seems to be failing, which also mean that the current implementation of `MarkCommandTest` is broken too.

I'll look into `mark` command test cases. 😓

2017-03-26 12:50 UTC, xbili commented on .project
> +		<nature>net.sf.eclipsecs.core.CheckstyleNature</nature>
What is this?

2017-03-26 12:50 UTC, xbili commented on src/main/java/seedu/opus/logic/parser/DateTimeParser.java
> +        Parser parser = new Parser();
This `Parser` is very confusing since we have our own `Parser` class as well. Maybe name this variable as `dateTimeParser` or something clearer?

2017-03-26 12:50 UTC, xbili commented on src/main/java/seedu/opus/logic/parser/DateTimeParser.java
> +
Minor issue, but too much whitespace here. 😅

2017-03-26 12:50 UTC, xbili commented on src/main/java/seedu/opus/logic/parser/ScheduleCommandParser.java
> +            }
I'll create a new issue to refactor the usage of `Optional` throughout our codebase. `isPresent` shouldn't be used this way, we can change a lambda to do something if `isPresent` passes in a much cleaner way. 

Can see [this](http://www.nurkiewicz.com/2013/08/optional-in-java-8-cheat-sheet.html).

2017-03-26 12:50 UTC, xbili commented on src/test/java/guitests/ScheduleCommandTest.java
> +        // trailing whitespace after command should be considered as a invalid command
Hmm, this seems odd. IIRC the rest of our commands trims the trailing whitespace. Is there a reason for this?

2017-03-26 16:46 UTC, gjlam95 commented on src/main/java/seedu/opus/logic/parser/ScheduleCommandParser.java
> +            }
Agree, will be looking into Lambda next to remove the use of 'isPresent' and conditional variables

2017-03-26 17:15 UTC, hlynn93 commented on src/test/java/guitests/ScheduleCommandTest.java
> +        // trailing whitespace after command should be considered as a invalid command
EditCommand has it too. I believe this is to ensure whether the command gets trimmed or not?

2017-03-26 17:15 UTC, hlynn93 commented on src/main/java/seedu/opus/logic/parser/ScheduleCommandParser.java
> +            }
Thanks for pointing that out. Just changed into lambda functions

2017-03-27 01:14 UTC, hlynn93 commented
@xbili does it still fail? :/

2017-03-27 09:41 UTC, xbili commented
@hlynn93 Yup it's fine now! Thanks!

2017-03-27 09:41 UTC, xbili approved these changes

2017-03-27 09:41 UTC, xbili commented
:shipit:

2017-03-27 10:09 UTC, merged