Sort command
CS2103JAN2017-W15-B3/main pull request #179
Opened 2017-03-26 14:11 UTC by gjlam95

2017-03-26 16:45 UTC, gjlam95 commented
Yet to implement sort command accepting multiple parameters for sorting.
Pending date time format to change.

2017-03-26 17:09 UTC, hlynn93 commented
@gjlam95 is the date time fine now after the fix?

2017-03-27 09:47 UTC, xbili commented on src/main/java/seedu/opus/logic/commands/SortCommand.java
> +        if (keyword.contains("all") || keyword.contains("status") || keyword.contains("priority")
IMO it's cleaner to put these commands into an `Array`, iterate through it and if `keyword` contains that command, then return.

Small matter, it's fine without changing too :)

2017-03-27 09:52 UTC, xbili requested changes
Should be fine after the minor changes! 👍

2017-03-27 09:52 UTC, xbili commented on src/main/java/seedu/opus/logic/commands/SortCommand.java
> +                || keyword.contains("start") || keyword.contains("end")) {
IMO it might be cleaner to put the commands into a static array called `SORTABLE_BY` and loop through it to check.

2017-03-27 09:52 UTC, xbili commented on src/main/java/seedu/opus/model/comparators/EndTimeComparator.java
> +            } else if (d1.getEndTime().get().dateTime.isAfter(d2.getEndTime().get().dateTime)) {
These two long optional chains can be refactored for better readability too!

2017-03-27 09:52 UTC, xbili commented on src/main/java/seedu/opus/model/comparators/StartTimeComparator.java
> +            } else if (d1.getStartTime().get().dateTime.isAfter(d2.getStartTime().get().dateTime)) {
Same here.

2017-03-27 09:52 UTC, xbili commented on src/main/java/seedu/opus/model/task/UniqueTaskList.java
> +            break;
These commands in strings should be declared as a `static` variables in the `SortCommand` class, so we don't have to look through the entire codebase to change the behaviors of the command. 

Maybe name them `BY_ALL`, `BY_PRIORITY` etc.

2017-03-27 09:52 UTC, xbili commented on src/test/java/guitests/EditCommandTest.java
> +        int taskManagerIndex = 4;
What's the reason for decreasing this by one? o.o

2017-03-27 09:53 UTC, hlynn93 requested changes

2017-03-27 09:53 UTC, hlynn93 commented on src/main/java/seedu/opus/logic/commands/SortCommand.java
> +        if (keyword.contains("all") || keyword.contains("status") || keyword.contains("priority")
I believe you could have an array of all the possible keywords and do something like this
http://stackoverflow.com/questions/8992100/test-if-a-string-contains-any-of-the-strings-from-an-array

2017-03-27 09:53 UTC, hlynn93 commented on src/main/java/seedu/opus/model/comparators/EndTimeComparator.java
> +        boolean hasStartOrEnd = d1.getEndTime().isPresent() || d2.getEndTime().isPresent();
The variable names confuse me. These two lines check whether both or either task has StartTime or not right? So it should be something like `bothHasStart` or sth? It's the same for StartTimeComparator as well.

2017-03-27 09:53 UTC, hlynn93 commented on src/main/java/seedu/opus/model/comparators/EndTimeComparator.java
> +            return -1;
what's the logic here? 
Should it be like 
```
if (d1.getEndTime().isPresent()) 
    return -1;
else 
     return 1;
```

2017-03-27 13:08 UTC, xbili approved these changes

2017-03-27 13:12 UTC, hlynn93 approved these changes

2017-03-27 13:13 UTC, merged