Include more commands in list of autocomplete commands
CS2103JAN2017-W15-B3/main pull request #252
Opened 2017-04-08 15:07 UTC by xbili

`sort`, `sync`, `save`, `exit`.

2017-04-08 16:30 UTC, mynameisyz requested changes

2017-04-08 16:30 UTC, mynameisyz commented on src/main/java/seedu/opus/ui/CommandBox.java
> +        private static final String[] COMMANDS = { "add", "delete", "edit", "mark", "schedule", "list",
Wouldn't it be better to use AddCommand.COMMAND_WORD etc instead of magic strings?

2017-04-09 01:04 UTC, xbili commented on src/main/java/seedu/opus/ui/CommandBox.java
> +        private static final String[] COMMANDS = { "add", "delete", "edit", "mark", "schedule", "list",
Ah yes, totally forgot about that! Will change it.

2017-04-09 03:47 UTC, mynameisyz approved these changes

2017-04-09 06:15 UTC, merged