UI component clean-up
CS2103JAN2017-W15-B3/main pull request #49
Opened 2017-03-08 15:01 UTC by xbili

Cleaned up the remaining traces of `AddressBook`, `person` etc. in the UI component.

2017-03-09 08:47 UTC, gjlam95 commented on src/main/java/seedu/address/ui/MainWindow.java
>      public PersonListPanel getPersonListPanel() {
Are we gonna keep the method name as getPersonListPanel instead of changing to getTaskListPanel for now?

2017-03-09 08:47 UTC, gjlam95 commented on src/main/java/seedu/address/ui/MainWindow.java
>      private AnchorPane getPersonListPlaceholder() {
As per previous comment

2017-03-09 08:55 UTC, lamgj requested changes

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/guihandles/PersonListPanelHandle.java
> +    public TaskCardHandle navigateToPerson(ReadOnlyTask person) {
Do we stick to navigateToPerson method name for now or to change it to navigateToTask?

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/seedu/address/testutil/TestUtil.java
> +    public static boolean compareCardAndPerson(TaskCardHandle card, ReadOnlyTask person) {
ReadOnlyTask object should be declared as task instead of person

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/AddressBookGuiTest.java
>       * Asserts the person shown in the card is same as the given person
To change comment to task instead of person

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/AddressBookGuiTest.java
> +    public void assertMatching(ReadOnlyTask person, TaskCardHandle card) {
ReadOnlyTask object should be task instead of person

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/EditCommandTest.java
>          // confirm the list now contains all previous persons plus the person with updated details
Change person to task in comment

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/guihandles/PersonListPanelHandle.java
>          final Optional<ReadOnlyTask> person = getListView().getItems().stream()
Object to be declared as task instead of person

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/guihandles/PersonListPanelHandle.java
> +    public TaskCardHandle getPersonCardHandle(ReadOnlyTask person) {
Object to be declared as task instead of person

2017-03-09 08:55 UTC, gjlam95 commented on src/test/java/guitests/guihandles/TaskCardHandle.java
>   * Provides a handle to a person card in the person list panel.
Change person to task in comment

2017-03-09 13:04 UTC, hlynn93 reviewed
Should we change the interface methods like navigateToPerson within our own components so that when we merge, everything comes together?

2017-03-09 13:04 UTC, hlynn93 commented on src/test/java/guitests/guihandles/PersonListPanelHandle.java
>      public PersonListPanelHandle(GuiRobot guiRobot, Stage primaryStage) {
rename this file to TaskListPanelHandle?

2017-03-09 13:04 UTC, hlynn93 commented on src/test/java/guitests/AddressBookGuiTest.java
>  import guitests.guihandles.CommandBoxHandle;
Rename this file to TaskManagerGuiTest.

2017-03-10 13:38 UTC, xbili commented on src/test/java/guitests/guihandles/PersonListPanelHandle.java
>      public PersonListPanelHandle(GuiRobot guiRobot, Stage primaryStage) {
I'll leave this out first because of other tests' dependency on this.

2017-03-10 13:51 UTC, xbili commented
@gjlam95 @hlynn93 made changes to the code reviewed. If it's fine, approve it and merge! :)

2017-03-10 15:27 UTC, lamgj approved these changes

2017-03-10 15:39 UTC, xbili commented
@gjlam95 conflict resolved!

2017-03-10 15:50 UTC, merged