Refactor model
CS2103JAN2017-W15-B3/main pull request #51
Opened 2017-03-09 15:05 UTC by hlynn93

2017-03-09 17:12 UTC, xbili requested changes

2017-03-09 17:12 UTC, xbili commented on src/main/java/seedu/address/commons/events/model/TaskManagerChangedEvent.java
>  /** Indicates the AddressBook in the model has changed*/
`TaskManager` instead of `AddressBook`.

2017-03-09 17:12 UTC, xbili commented on src/main/java/seedu/address/model/ModelManager.java
> +        int addressBookIndex = filteredTasks.getSourceIndex(filteredTaskListIndex);
`taskManagerIndex` instead of `addressBookIndex`.

2017-03-09 17:12 UTC, xbili commented on src/main/java/seedu/address/model/task/Name.java
>              "Person names should only contain alphanumeric characters and spaces, and it should not be blank";
Change the `Person` in constraint message too!

2017-03-09 17:12 UTC, xbili commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +    private void handleLocalModelChangedEvent(TaskManagerChangedEvent abce) {
`abce` stands for `AddressBookChangedEvent`, perhaps `tmce` would make more sense here.

2017-03-10 08:04 UTC, lamgj approved these changes

2017-03-10 15:07 UTC, xbili approved these changes

2017-03-10 15:24 UTC, merged